groups:
  - name: 'redis-info'
    rules:
      - alert: 'Redis Memory Use'
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
        for: 30s
        labels:
          serverity: warn
        annotations:
          summary: "env:[{{$labels.env}}] 实例 [{{$labels.addr}}]（{{$labels.alias}}） 使用内存超过阈值"
          description: "env:[{{$labels.env}}] 实例 [{{$labels.addr}}]（{{$labels.alias}}） 使用内存超过 80%。（当前值：{{$value}}%）"
