{
 "title": "DMS 系统业务看板",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"ck-goku\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"ck-goku\"}*1000"
    }
   ]
  },
  {
   "title": "$application - 系统负载",
   "type": "graph",
   "description": "1m 内系统负载",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "repeat": "application",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\"}",
     "legendFormat": "负载-{{instance}}-{{env}}"
    }
   ]
  },
  {
   "title": "$application-内存",
   "type": "graph",
   "description": "应用内存",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "repeat": "application",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\"}) by (instance)",
     "legendFormat": "{{instance}} - Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\"}) by (instance)",
     "legendFormat": "{{instance}} - Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\"}) by (instance)",
     "legendFormat": "{{instance}} - Max"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"ck-goku\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"ck-goku\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"ck-goku\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"ck-goku\",area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "$application -  线程",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "repeat": "application",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live{application=\"$application\"}",
     "legendFormat": "活动 - {{instance}}"
    },
    {
     "expr": "jvm_threads_daemon{application=\"$application\"}",
     "legendFormat": "守护 - {{instance}}"
    },
    {
     "expr": "jvm_threads_peak{application=\"$application\"}",
     "legendFormat": "最高 - {{instance}}"
    },
    {
     "expr": "jvm_threads_live_threads{application=\"$application\"}",
     "legendFormat": "活动 - {{instance}}"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$application\"}",
     "legendFormat": "守护 - {{instance}}"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$application\"}",
     "legendFormat": "最高 - {{instance}}"
    }
   ]
  },
  {
   "title": "Http/Servlet Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"ck-goku\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    },
    {
     "expr": "sum(rate(tomcat_servlet_error_total{application=\"ck-goku\"}[1m]))",
     "legendFormat": "tomcat_servlet_error"
    }
   ]
  },
  {
   "title": "$application - CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "repeat": "application",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"$application\"}",
     "legendFormat": "jvm - {{instance}}-{{env}}"
    },
    {
     "expr": "system_cpu_usage{applicatioin=\"$application\"}",
     "legendFormat": "system - {{instance}}-{{env}}"
    }
   ]
  },
  {
   "title": "部署概要",
   "type": "graph",
   "description": "分钟级别",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dms_deployment_total{triggerBy=\"normal\"}[1m])",
     "legendFormat": "公司DMS"
    },
    {
     "expr": "increase(dms_deployment_total{triggerBy=\"rundeck\"}[1m])",
     "legendFormat": "开发测试"
    },
    {
     "expr": "increase(dms_deployment_finish_total{triggerBy=\"rundeck\"}[1m])",
     "legendFormat": "开发测试 - {{status}}"
    }
   ]
  },
  {
   "title": "构建概要",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dms_build_finish_total[5m])",
     "legendFormat": "构建结果 {{status}}"
    },
    {
     "expr": "increase(dms_build_jenkins_start_total[5m])",
     "legendFormat": "jenkins 开始构建 {{status}}"
    },
    {
     "expr": "increase(dms_build_jenkins_trigger_total[5m])",
     "legendFormat": "系统内 jenkins 触发 {{status}}"
    }
   ]
  },
  {
   "title": "git 概要",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dms_git_push_total[1m])",
     "legendFormat": "接收推送 {{status}}"
    },
    {
     "expr": "increase(dms_git_update_total[1m])",
     "legendFormat": "系统更新 {{obj}} - cause [{{cause}}]"
    }
   ]
  },
  {
   "title": "部署异常状态关注",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dms_deployment_finish_total{status!=\"success\"}[5m])",
     "legendFormat": "{{triggerBy}} 部署 - {{status}}"
    },
    {
     "expr": "dms_deployment_total{triggerBy=\"rundeck\"} - on (triggerBy) (sum(dms_deployment_finish_total{triggerBy=\"rundeck\"}) by (triggerBy))",
     "legendFormat": "部署中（未反馈结果）"
    }
   ]
  },
  {
   "title": "构建异常状态关注",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dms_build_finish_total{status!=\"suc\"}",
     "legendFormat": "未成功构建"
    },
    {
     "expr": "dms_build_jenkins_trigger_total{status=\"msgReceive\"} - on(application) dms_build_jenkins_trigger_total{status=\"triggered\"}",
     "legendFormat": "未传递到 Jenkins "
    },
    {
     "expr": "dms_build_jenkins_trigger_total{status=\"triggered\"} - on(application)  dms_build_jenkins_start_total{status=\"ing\"}",
     "legendFormat": "未开始构建"
    },
    {
     "expr": "dms_build_jenkins_start_total{status=\"ing\"} - on (application) sum(dms_build_finish_total) by (application)",
     "legendFormat": "未反馈结果"
    }
   ]
  },
  {
   "title": "git 异常状态关注",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dms_git_push_total - on (application) dms_git_update_total{obj=\"repo\"}",
     "legendFormat": "未成功更新仓库"
    },
    {
     "expr": "dms_git_update_total{obj=\"repo\"} - ignoring(obj) dms_git_update_total{obj=\"branch\"}",
     "legendFormat": "未成功更新分支"
    },
    {}
   ]
  }
 ]
}