{
 "title": "Java Apps - 详情",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot)",
 "tags": [
  "java",
  "apps"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "env",
    "label": "env",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"},env)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate - 总",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[20s]))",
       "legendFormat": "HTTP"
      },
      {
       "expr": "sum(rate(tomcat_servlet_request_seconds_count{application=\"$application\", instance=\"$instance\"}[20s]))",
       "legendFormat": "tomcat_servlet_request"
      }
     ]
    },
    {
     "title": "Http/Servlet Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[20s]))",
       "legendFormat": "HTTP - 5xx"
      },
      {
       "expr": "sum(rate(tomcat_servlet_error_total{application=\"$application\", instance=\"$instance\"}[1m]))",
       "legendFormat": "tomcat_servlet_error"
      }
     ]
    },
    {
     "title": "总平均和最大时长",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[20s]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[20s]))",
       "legendFormat": "HTTP - AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status!~\"5..\"})",
       "legendFormat": "HTTP - MAX"
      },
      {
       "expr": "sum(rate(tomcat_servlet_request_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m]))/sum(rate(tomcat_servlet_request_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
       "legendFormat": "tomcat_request - AVG"
      }
     ]
    },
    {
     "title": "tomcat threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tomcat_threads_busy_threads{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "TOMCAT - BUSY"
      },
      {
       "expr": "sum(tomcat_threads_current_threads{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "TOMCAT - CURRENT"
      },
      {
       "expr": "sum(tomcat_threads_config_max_threads{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "TOMCAT - MAX"
      }
     ]
    },
    {
     "title": "Rate - 详细",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[20s])",
       "legendFormat": "[{{method}} - {{status}}] {{uri}}"
      }
     ]
    },
    {
     "title": "Http/Servlet Errors - 详细",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[20s])",
       "legendFormat": "[{{method}} - {{status}}] {{uri}}"
      }
     ]
    },
    {
     "title": "平均时长 - 详细",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[20s]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[20s])",
       "legendFormat": "[{{method}} - {{status}}] {{uri}}"
      }
     ]
    },
    {
     "title": "最大时长 -  详细",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status!~\"5..\"}",
       "legendFormat": "MAX - [{{method}} - {{status}}] {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dubbo Invoke",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dubbo Invoke Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dubbo_service_invoke_seconds_count{application=\"$application\", instance=\"$instance\", side=\"provider\", provider!=\"com.alibaba.dubbo.monitor.MonitorService\"}[20s]))",
       "legendFormat": "总 [Provider] 平均请求频率"
      },
      {
       "expr": "sum(rate(dubbo_service_invoke_seconds_count{application=\"$application\", instance=\"$instance\", side=\"consumer\", provider!=\"com.alibaba.dubbo.monitor.MonitorService\"}[20s]))",
       "legendFormat": "总 [Consumer] 平均请求频率"
      }
     ]
    },
    {
     "title": "Dubbo Invoke 总体调用次数概览",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dubbo_service_invoke_seconds_count{application=\"$application\", instance=\"$instance\", side=\"provider\", provider!=\"com.alibaba.dubbo.monitor.MonitorService\"}[20s]))",
       "legendFormat": "总 [Provider] 请求数"
      },
      {
       "expr": "sum(increase(dubbo_service_invoke_seconds_count{application=\"$application\", instance=\"$instance\", side=\"consumer\", provider!=\"com.alibaba.dubbo.monitor.MonitorService\"}[20s]))",
       "legendFormat": "总 [Consumer]] 请求数"
      }
     ]
    },
    {
     "title": "Dubbo Invoke Errors 总体概览",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dubbo_service_invoke_seconds_count{application=\"$application\", instance=\"$instance\", side=\"provider\", result=\"fail\"}[20s]))",
       "legendFormat": "总 [Provider] 错误数"
      },
      {
       "expr": "sum(increase(dubbo_service_invoke_seconds_count{application=\"$application\", instance=\"$instance\", side=\"consumer\", result=\"fail\"}[20s]))",
       "legendFormat": "总 [Consumer]] 错误数"
      }
     ]
    },
    {
     "title": "Dubbo Invoke 耗时总体概览",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dubbo_service_invoke_seconds_sum{application=\"$application\", instance=\"$instance\", side=\"provider\", result=\"suc\", provider!=\"com.alibaba.dubbo.monitor.MonitorService\"}[20s]))/sum(rate(dubbo_service_invoke_seconds_count{application=\"$application\", instance=\"$instance\", side=\"provider\", result=\"suc\", provider!=\"com.alibaba.dubbo.monitor.MonitorService\"}[20s]))",
       "legendFormat": "总 - [Provider] Dubbo - 平均耗时"
      },
      {
       "expr": "max(dubbo_service_invoke_seconds_max{application=\"$application\", instance=\"$instance\", side=\"provider\", result=\"suc\", provider!=\"com.alibaba.dubbo.monitor.MonitorService\"})",
       "legendFormat": "总 - [Provider]  - 最大耗时"
      },
      {
       "expr": "sum(rate(dubbo_service_invoke_seconds_sum{application=\"$application\", instance=\"$instance\", side=\"consumer\", result=\"suc\", provider!=\"com.alibaba.dubbo.monitor.MonitorService\"}[20s]))/sum(rate(dubbo_service_invoke_seconds_count{application=\"$application\", instance=\"$instance\", side=\"consumer\", result=\"suc\", provider!=\"com.alibaba.dubbo.monitor.MonitorService\"}[20s]))",
       "legendFormat": "总 - [Consumer] Dubbo - 平均耗时"
      },
      {
       "expr": "max(dubbo_service_invoke_seconds_max{application=\"$application\", instance=\"$instance\", side=\"consumer\", result=\"suc\", provider!=\"com.alibaba.dubbo.monitor.MonitorService\"})",
       "legendFormat": "总 - [Consumer]  - 最大耗时"
      }
     ]
    },
    {
     "title": "Dubbo Invoke 最大并发数",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "dubbo_service_invoke_concurrent{application=\"$application\", instance=\"$instance\", provider!=\"com.alibaba.dubbo.monitor.MonitorService\"}",
       "legendFormat": "[{{side}}] {{provider}}#{{method}} [{{result}}] g:{{group}}-v:{{version}}"
      }
     ]
    },
    {
     "title": "Dubbo Invoke 具体服务调用次数",
     "type": "graph",
     "description": "注意，数据并不准确，为根据数值推算的值",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(dubbo_service_invoke_seconds_count{application=\"$application\", instance=\"$instance\", provider!=\"com.alibaba.dubbo.monitor.MonitorService\"}[20s])",
       "legendFormat": "[{{side}}] {{provider}}#{{method}} [{{result}}] g:{{group}}-v:{{version}}"
      }
     ]
    },
    {
     "title": "Dubbo Invoke Errors 具体服务",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(dubbo_service_invoke_seconds_count{application=\"$application\", instance=\"$instance\", side=\"provider\", result=\"fail\"}[20s])",
       "legendFormat": "[{{side}}] {{provider}}#{{method}} [{{result}}] g:{{group}}-v:{{version}}"
      }
     ]
    },
    {
     "title": "Dubbo 最大处理时间",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "dubbo_service_invoke_seconds_max{application=\"$application\", instance=\"$instance\", provider!=\"com.alibaba.dubbo.monitor.MonitorService\"}",
       "legendFormat": "[{{side}}] {{provider}}#{{method}} [{{result}}] g:{{group}}-v:{{version}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "max"
      },
      {
       "expr": "process_memory_rss_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "rss"
      },
      {
       "expr": "process_memory_pss_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "pss"
      },
      {
       "expr": "process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "swap"
      },
      {
       "expr": "process_memory_swappss_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "swappss"
      },
      {
       "expr": "process_memory_pss_bytes{application=\"$application\", instance=\"$instance\"} + process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "phys (pss+swap)"
      }
     ]
    },
    {
     "title": "JVM Native Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(process_memory_pss_bytes{application=\"$application\", instance=\"$instance\"} + process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}  - on(application,instance) sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\"})  by(application,instance)) >= 0",
       "legendFormat": "native"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{application=\"$application\", instance=\"$instance\"}[1h])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "system-1m"
      },
      {},
      {
       "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_threads{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "process"
      },
      {
       "expr": "jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon_threads{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak_threads{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "peak"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_max_fds{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "max"
      },
      {
       "expr": "process_files_open_files{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_files_max_files{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Log Events (1m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "loaded"
      },
      {
       "expr": "jvm_classes_unloaded_classes_total{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "unloaded"
      }
     ]
    },
    {
     "title": "Class load/unload rate (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded_classes{application=\"$application\",instance=\"$instance\"}[5m])",
       "legendFormat": "class load rate"
      },
      {
       "expr": "delta(jvm_classes_unloaded_classes_total{application=\"$application\",instance=\"$instance\"}[5m])",
       "legendFormat": "class unload rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{application=\"$application\", instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{application=\"$application\", instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Database base metrics",
   "type": "graph",
   "description": "公共的数据基础的一些度量（兼容 springboot 配置）",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jdbc_connections_active{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "jdbc- active"
    },
    {
     "expr": "jdbc_connections_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "jdbc- MAX"
    },
    {
     "expr": "jdbc_connections_min{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "jdbc- MIN"
    }
   ]
  },
  {
   "title": "Database Druid 基础指标",
   "type": "graph",
   "description": "Druid 特有的基本 metrics 参数，基本参数波动",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jdbc_druid_active{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "druid- active"
    },
    {
     "expr": "jdbc_druid_maxActive{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "druid- MAX"
    },
    {
     "expr": "jdbc_druid_minIdle{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "druid- MIN"
    },
    {
     "expr": "jdbc_druid_pooling{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "druid- pooling"
    },
    {
     "expr": "jdbc_druid_initialSize{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "druid- initialSize"
    },
    {
     "expr": "jdbc_druid_activePeak{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "druid- activePeak"
    },
    {
     "expr": "jdbc_druid_poolingPeak{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "druid- poolingPeak"
    },
    {
     "expr": "jdbc_druid_notEmptyWaitThread{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "druid- notEmptyWaitThread"
    },
    {
     "expr": "jdbc_druid_notEmptyWaitThreadPeak{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "druid- notEmptyWaitThreadPeak"
    }
   ]
  },
  {
   "title": "Database Druid SQL 执行",
   "type": "graph",
   "description": "Druid 特有的 sql 执行情况",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jdbc_druid_execute{application=\"$application\", instance=\"$instance\"}[20s])",
     "legendFormat": "druid- execute"
    },
    {
     "expr": "increase(jdbc_druid_executeQuery{application=\"$application\", instance=\"$instance\"}[20s])",
     "legendFormat": "druid- query"
    },
    {
     "expr": "increase(jdbc_druid_executeUpdate{application=\"$application\", instance=\"$instance\"}[20s])",
     "legendFormat": "druid- update"
    },
    {
     "expr": "increase(jdbc_druid_executeBatch{application=\"$application\", instance=\"$instance\"}[20s])",
     "legendFormat": "druid- batch"
    }
   ]
  },
  {
   "title": "Database Druid 异常",
   "type": "graph",
   "description": "Druid 特有的 连接异常情况",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jdbc_druid_discard{application=\"$application\", instance=\"$instance\"}[20s])",
     "legendFormat": "druid- discard"
    },
    {
     "expr": "increase(jdbc_druid_removeAbandoned{application=\"$application\", instance=\"$instance\"}[20s])",
     "legendFormat": "druid- removeAbandoned"
    },
    {
     "expr": "increase(jdbc_druid_connectError{application=\"$application\", instance=\"$instance\"}[20s])",
     "legendFormat": "druid- connectError"
    },
    {
     "expr": "increase(jdbc_druid_recycleError{application=\"$application\", instance=\"$instance\"}[20s])",
     "legendFormat": "druid- batch"
    }
   ]
  },
  {
   "title": "Database Druid 连接创建销毁",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jdbc_druid_create{application=\"$application\", instance=\"$instance\"}[60s])",
     "legendFormat": "druid- create"
    },
    {
     "expr": "increase(jdbc_druid_destroy{application=\"$application\", instance=\"$instance\"}[60s])",
     "legendFormat": "druid- destroy"
    }
   ]
  },
  {
   "title": "Database Druid 连接（池）获取释放",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jdbc_druid_connect{application=\"$application\", instance=\"$instance\"}[20s])",
     "legendFormat": "druid- connect"
    },
    {
     "expr": "increase(jdbc_druid_close{application=\"$application\", instance=\"$instance\"}[20s])",
     "legendFormat": "druid- close"
    },
    {
     "expr": "increase(jdbc_druid_recycle{application=\"$application\", instance=\"$instance\"}[20s])",
     "legendFormat": "druid- recyle"
    }
   ]
  }
 ]
}