{
 "title": "metis-mount-default",
 "description": "基础服务业务度量",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "env", "query": "label_values(env)" }
  ]
 },
 "panels": [
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "mickey平台在线",
   "type": "singlestat",
   "description": "mickey平台是否在线",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "probe_success{instance=~\"http://linglongta.vemic.com.*/login\"}"
    }
   ]
  },
  {
   "title": "mail平台在线",
   "type": "singlestat",
   "description": "mail平台是否在线",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "round(avg(metis_mail_access))" }
   ]
  },
  {
   "title": "SMS平台在线",
   "type": "singlestat",
   "description": "SMS平台是否在线",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "probe_success{instance=~\".*/sms/services/MessageTransferWebService\"}"
    }
   ]
  },
  {
   "title": "LDAP 域名在线",
   "type": "singlestat",
   "description": "LDAP 域名认证平台是否在线",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(avg(metis_domain_access))"
    }
   ]
  },
  {
   "title": "FFS在线",
   "type": "singlestat",
   "description": "FFS是否在线",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "round(avg(metis_ffs_access))" }
   ]
  },
  { "title": "sms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "24H收发统计",
   "type": "table",
   "description": "短信接收请求及发送情况24H累计统计",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "round(sum(increase(metis_sms_request_total{priority=\"high\",env=\"$env\"}[1d])))",
     "legendFormat": "短信请求(优先级: high, 环境: $env)"
    },
    {
     "expr": "round(sum(increase(metis_sms_request_total{priority=\"middle\",env=\"$env\"}[1d])))",
     "legendFormat": "短信请求(优先级: middle, 环境: $env)"
    },
    {
     "expr": "round(sum(increase(metis_sms_request_total{priority=\"lower\",env=\"$env\"}[1d])))",
     "legendFormat": "短信请求(优先级: lower, 环境: $env)"
    },
    {
     "expr": "round(sum(increase(metis_sms_send_total{status=\"success\",env=\"$env\"}[1d])))",
     "legendFormat": "短信发送(状态: success, 环境: $env)"
    },
    {
     "expr": "round(sum(increase(metis_sms_send_total{status=\"fail\",env=\"$env\"}[1d])))",
     "legendFormat": "短信发送(状态: fail, 环境: $env)"
    }
   ]
  },
  {
   "title": "5分钟累计发送量变化",
   "type": "graph",
   "description": "5分钟累计发送量变化",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(metis_sms_send_total{status=\"success\",env=\"$env\"}[5m])))",
     "legendFormat": "success($env)"
    },
    {
     "expr": "round(sum(increase(metis_sms_send_total{status=\"fail\",env=\"$env\"}[5m])))",
     "legendFormat": "fail($env)"
    }
   ]
  },
  { "title": "mail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "24H收发统计",
   "type": "table",
   "description": "邮件接收请求及发送情况24H累计统计",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "round(sum(increase(metis_mail_request_total{env=\"$env\"}[1d])))",
     "legendFormat": "邮件请求(环境: $env)"
    },
    {
     "expr": "round(sum(increase(metis_mail_send_total{status=\"success\",env=\"$env\"}[1d])))",
     "legendFormat": "邮件发送(状态: success, 环境: $env)"
    },
    {
     "expr": "round(sum(increase(metis_mail_send_total{status=\"fail\",env=\"$env\"}[1d])))",
     "legendFormat": "邮件发送(状态: fail, 环境: $env)"
    }
   ]
  },
  {
   "title": "5分钟累计发送量变化",
   "type": "graph",
   "description": "5分钟累计发送量变化",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(metis_mail_send_total{status=\"success\",env=\"$env\"}[5m])))",
     "legendFormat": "success($env)"
    },
    {
     "expr": "round(sum(increase(metis_mail_send_total{status=\"fail\",env=\"$env\"}[5m])))",
     "legendFormat": "fail($env)"
    }
   ]
  }
 ]
}