{
 "title": "应用大盘",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "application", "label": "应用", "query": "label_values(application)" }
  ]
 },
 "panels": [
  {
   "title": "当前告警数量",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ALERTS) or vector(0)" }
   ]
  },
  {
   "title": "高 CPU 占用",
   "type": "graph",
   "description": "只统计存在大于 10% 占用的部分应用",
   "gridPos": { "h": 7, "w": 11, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage > 0.1 and topk(5, system_cpu_usage)",
     "legendFormat": "[{{env}}] {{application}} - {{instance}}"
    }
   ]
  },
  {
   "title": "高堆内存占用",
   "type": "graph",
   "description": "只统计存在大于 50% 堆内存占用的部分应用",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(jvm_memory_used_bytes{area=\"heap\"}) by (application, instance) / sum(jvm_memory_max_bytes{area=\"heap\"}) by (application, instance)) > 0.5",
     "legendFormat": "[{{env}}] {{application}} - {{instance}}"
    },
    {}
   ]
  },
  {
   "title": "告警记录",
   "type": "table",
   "description": "在右上角时间范围内的告警记录",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  {
   "title": "各应用各实例告警",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ALERTS",
     "legendFormat": "[{{application}}]{{alertname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "$application - 系统负载",
   "type": "graph",
   "description": "1m 内系统负载",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "repeat": "application",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\"}",
     "legendFormat": "负载-{{instance}}-{{env}}"
    }
   ]
  },
  {
   "title": "$application - CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "repeat": "application",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"$application\"}",
     "legendFormat": "jvm - {{instance}}-{{env}}"
    },
    {
     "expr": "system_cpu_usage{applicatioin=\"$application\"}",
     "legendFormat": "system - {{instance}}-{{env}}"
    }
   ]
  },
  {
   "title": "$application-内存",
   "type": "graph",
   "description": "应用内存",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "repeat": "application",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\"}) by (instance)",
     "legendFormat": "{{instance}} - Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\"}) by (instance)",
     "legendFormat": "{{instance}} - Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\"}) by (instance)",
     "legendFormat": "{{instance}} - Max"
    }
   ]
  },
  {
   "title": "$application -  线程",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "repeat": "application",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live{application=\"$application\"}",
     "legendFormat": "活动 - {{instance}}"
    },
    {
     "expr": "jvm_threads_daemon{application=\"$application\"}",
     "legendFormat": "守护 - {{instance}}"
    },
    {
     "expr": "jvm_threads_peak{application=\"$application\"}",
     "legendFormat": "最高 - {{instance}}"
    },
    {
     "expr": "jvm_threads_live_threads{application=\"$application\"}",
     "legendFormat": "活动 - {{instance}}"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$application\"}",
     "legendFormat": "守护 - {{instance}}"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$application\"}",
     "legendFormat": "最高 - {{instance}}"
    }
   ]
  }
 ]
}